// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

//! Documentation for execution plan metrics.
//!
//! Mirrors the pattern established by [`crate::Documentation`] for UDFs.
//! Each execution plan exposes a `MetricsDocumentation` describing the metrics
//! it emits, and the doc generation script collects these via
//! `SessionStateDefaults::default_metric_docs()`.

/// Where a metrics struct should appear in generated documentation.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum MetricPosition {
    /// Reused across many operators (e.g. `BaselineMetrics`).
    Common,
    /// Specific to one operator.
    Operator,
}

/// Documentation for a single metric field within a metrics struct.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct MetricFieldDocumentation {
    /// Metric name as it appears at runtime (matches the string passed to
    /// `MetricBuilder::counter`, `subset_time`, etc.).
    pub name: String,
    /// Human readable description in markdown.
    pub description: String,
}

/// Documentation describing the metrics emitted by an execution plan.
///
/// Created via [`MetricsDocumentation::builder`]. The DataFusion metrics
/// documentation page is generated by iterating
/// `SessionStateDefaults::default_metric_docs()` and rendering each entry.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct MetricsDocumentation {
    /// Display name for the documentation entry. For operator-specific
    /// metrics this is the `ExecutionPlan` name (e.g. `FilterExec`).
    /// For common metrics this is the metrics struct name
    /// (e.g. `BaselineMetrics`).
    pub name: String,
    /// Whether the entry is grouped under "Common Metrics" or
    /// "Operator-specific Metrics".
    pub position: MetricPosition,
    /// Markdown description shown above the metrics table.
    pub description: String,
    /// Metric fields in the order they should be rendered.
    pub metrics: Vec<MetricFieldDocumentation>,
}

impl MetricsDocumentation {
    /// Start building a new [`MetricsDocumentation`].
    pub fn builder(
        name: impl Into<String>,
        position: MetricPosition,
    ) -> MetricsDocumentationBuilder {
        MetricsDocumentationBuilder::new(name, position)
    }
}

/// Builder for [`MetricsDocumentation`].
#[derive(Debug, Clone)]
pub struct MetricsDocumentationBuilder {
    name: String,
    position: MetricPosition,
    description: String,
    metrics: Vec<MetricFieldDocumentation>,
}

impl MetricsDocumentationBuilder {
    fn new(name: impl Into<String>, position: MetricPosition) -> Self {
        Self {
            name: name.into(),
            position,
            description: String::new(),
            metrics: Vec::new(),
        }
    }

    /// Set the markdown description.
    pub fn with_description(mut self, description: impl Into<String>) -> Self {
        self.description = description.into();
        self
    }

    /// Append a metric field.
    pub fn with_metric(
        mut self,
        name: impl Into<String>,
        description: impl Into<String>,
    ) -> Self {
        self.metrics.push(MetricFieldDocumentation {
            name: name.into(),
            description: description.into(),
        });
        self
    }

    /// Finish and return the [`MetricsDocumentation`].
    pub fn build(self) -> MetricsDocumentation {
        MetricsDocumentation {
            name: self.name,
            position: self.position,
            description: self.description,
            metrics: self.metrics,
        }
    }
}
