# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# This file controls the settings of this repository
#
# See more details at
# https://cwiki.apache.org/confluence/display/INFRA/Git+-+.asf.yaml+features

notifications:
  commits: commits@datafusion.apache.org
  issues: github@datafusion.apache.org
  pullrequests: github@datafusion.apache.org
  discussions: github@datafusion.apache.org
  jira_options: link label worklog
github:
  description: "Apache DataFusion SQL Query Engine"
  homepage: https://datafusion.apache.org/
  labels:
    - arrow
    - big-data
    - dataframe
    - datafusion
    - olap
    - python
    - query-engine
    - rust
    - sql
  enabled_merge_buttons:
    squash: true
    squash_commit_message: PR_TITLE_AND_DESC
    merge: false
    rebase: false
  features:
    issues: true
    discussions: true
  protected_branches:
    main:
      required_pull_request_reviews:
        required_approving_review_count: 1
    # needs to be updated as part of the release process
    # .asf.yaml doesn't support wildcard branch protection rules, only exact branch names
    # https://github.com/apache/infrastructure-asfyaml?tab=readme-ov-file#branch-protection
    # Keeping set of protected branches for future releases
    # Meanwhile creating a prerelease script that will update the branch protection names
    # automatically. Keep track on it https://github.com/apache/datafusion/issues/17134
    branch-50:
      required_pull_request_reviews:
        required_approving_review_count: 1
    branch-51:
      required_pull_request_reviews:
        required_approving_review_count: 1
    branch-52:
      required_pull_request_reviews:
        required_approving_review_count: 1
    branch-53:
      required_pull_request_reviews:
        required_approving_review_count: 1
    branch-54:
      required_pull_request_reviews:
        required_approving_review_count: 1
    branch-55:
      required_pull_request_reviews:
        required_approving_review_count: 1
    branch-56:
      required_pull_request_reviews:
        required_approving_review_count: 1
    branch-57:
      required_pull_request_reviews:
        required_approving_review_count: 1
    branch-58:
      required_pull_request_reviews:
        required_approving_review_count: 1
    branch-59:
      required_pull_request_reviews:
        required_approving_review_count: 1
    branch-60:
      required_pull_request_reviews:
        required_approving_review_count: 1
    branch-61:
      required_pull_request_reviews:
        required_approving_review_count: 1
    branch-62:
      required_pull_request_reviews:
        required_approving_review_count: 1
    branch-63:
      required_pull_request_reviews:
        required_approving_review_count: 1
    branch-64:
      required_pull_request_reviews:
        required_approving_review_count: 1
    branch-65:
      required_pull_request_reviews:
        required_approving_review_count: 1
    branch-66:
      required_pull_request_reviews:
        required_approving_review_count: 1
    branch-67:
      required_pull_request_reviews:
        required_approving_review_count: 1
    branch-68:
      required_pull_request_reviews:
        required_approving_review_count: 1
    branch-69:
      required_pull_request_reviews:
        required_approving_review_count: 1
    branch-70:
      required_pull_request_reviews:
        required_approving_review_count: 1
  pull_requests:
    # enable updating head branches of pull requests
    allow_update_branch: true
    allow_auto_merge: true

# publishes the content of the `asf-site` branch to
# https://datafusion.apache.org/
publish:
  whoami: asf-site
