SELECT
SUM(c5) OVER(ORDER BY c13 ROWS BETWEEN 3 PRECEDING AND 1 FOLLOWING) as summation2,
SUM(c2) OVER(PARTITION BY c5 ORDER BY c13 ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) as summation10,
SUM(c2) OVER(PARTITION BY c1 ORDER BY c13 ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) as summation14,
SUM(c5) OVER(ORDER BY c5 ROWS BETWEEN 3 PRECEDING AND UNBOUNDED FOLLOWING) as summation5,
SUM(c5) OVER(ORDER BY c5 ROWS BETWEEN UNBOUNDED PRECEDING AND 2 FOLLOWING) as summation6,
SUM(c2) OVER(PARTITION BY c5, c7, c9 ORDER BY c13, c5 ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) as summation20,
SUM(c2) OVER(PARTITION BY c5 ORDER BY c13, c5 ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) as summation21
FROM test
ORDER BY c9;
