SELECT
SUM(c5) OVER(ORDER BY c13 ROWS BETWEEN 3 PRECEDING AND 1 FOLLOWING) as summation2,
SUM(c2) OVER(PARTITION BY c5 ORDER BY c13 ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) as summation10,
SUM(c2) OVER(PARTITION BY c1 ORDER BY c13 ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) as summation14,
SUM(c2) OVER(PARTITION BY c5, c7, c9 ORDER BY c13, c5 ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) as summation20,
SUM(c2) OVER(PARTITION BY c5 ORDER BY c13, c5 ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) as summation21,
CORR(c2, c5) OVER(ORDER BY c13 ROWS BETWEEN 3 PRECEDING AND 1 FOLLOWING) as corr2,
 CORR(c2, c3) OVER(ORDER BY c13 ROWS 3 PRECEDING) as corr3,
CORR(c2, c3) OVER(ORDER BY c13 ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) as corr6,
CORR(c2, c3) OVER(ORDER BY c13 ROWS UNBOUNDED PRECEDING) as corr7,
CORR(c4, c9) OVER(PARTITION BY c1 ORDER BY c13 ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) as corr10,
CORR(c4, c11) OVER(PARTITION BY c2 ORDER BY c13 ROWS UNBOUNDED PRECEDING) as corr11,
CORR(c4, c11) OVER(PARTITION BY c13 ORDER BY c13 ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) as corr14,
CORR(c4, c11) OVER(PARTITION BY c13 ORDER BY c13 ROWS UNBOUNDED PRECEDING) as corr15
FROM test;
