name: Bug report
description: Create a report to help us improve
type: Bug
labels: bug
body:
  - type: textarea
    attributes:
      label: Describe the bug
      description: Describe the bug.
      placeholder: >
        A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: To Reproduce
      placeholder: >
        Steps to reproduce the behavior:
  - type: textarea
    attributes:
      label: Expected behavior
      placeholder: >
        A clear and concise description of what you expected to happen.
  - type: textarea
    attributes:
      label: Additional context
      placeholder: >
        Add any other context about the problem here.
  - type: dropdown
    attributes:
      label: Willingness to contribute
      description: >
        The Apache DataFusion community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the Apache DataFusion codebase?
      options:
        - I plan to contribute a fix for this bug independently
        - I would like to contribute a fix for this bug, but request guidance from the DataFusion community
        - I cannot contribute a fix for this bug at this time
