// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

use proc_macro::TokenStream;
use quote::quote;
use syn::{DeriveInput, LitStr, parse_macro_input};

pub(crate) fn metrics_doc(args: TokenStream, input: TokenStream) -> TokenStream {
    let mut position: Option<LitStr> = None;
    let mut description: Option<LitStr> = None;
    let mut metrics: Vec<(Option<LitStr>, Option<LitStr>)> = vec![];

    let parser = syn::meta::parser(|meta| {
        if meta.path.is_ident("position") {
            position = Some(meta.value()?.parse()?);
            Ok(())
        } else if meta.path.is_ident("description") {
            description = Some(meta.value()?.parse()?);
            Ok(())
        } else if meta.path.is_ident("metric") {
            let mut entry: (Option<LitStr>, Option<LitStr>) = (None, None);
            let m = meta.parse_nested_meta(|meta| {
                if meta.path.is_ident("name") {
                    entry.0 = Some(meta.value()?.parse()?);
                    return Ok(());
                } else if meta.path.is_ident("description") {
                    entry.1 = Some(meta.value()?.parse()?);
                    return Ok(());
                }
                Ok(())
            });
            metrics.push(entry);
            m
        } else {
            Err(meta.error(format!("Unsupported property: {:?}", meta.path.get_ident())))
        }
    });

    parse_macro_input!(args with parser);

    let input = parse_macro_input!(input as DeriveInput);
    let name = input.ident.clone();
    let name_str = name.to_string();

    let position_expr = match position.as_ref().map(|p| p.value()) {
        Some(s) if s == "common" => {
            quote!(datafusion_doc::MetricPosition::Common)
        }
        Some(s) if s == "operator" => {
            quote!(datafusion_doc::MetricPosition::Operator)
        }
        Some(other) => {
            return syn::Error::new(
                position.as_ref().unwrap().span(),
                format!("position must be \"common\" or \"operator\" (got {other:?})"),
            )
            .to_compile_error()
            .into();
        }
        None => quote!(datafusion_doc::MetricPosition::Operator),
    };

    let description_expr = description
        .map(|d| quote!(.with_description(#d)))
        .unwrap_or_else(|| quote!());

    let metric_exprs: Vec<_> = metrics
        .iter()
        .map(|(name, desc)| match (name, desc) {
            (Some(n), Some(d)) => quote!(.with_metric(#n, #d)),
            _ => quote!(),
        })
        .collect();

    quote! {
        #input

        impl #name {
            /// Returns the documentation for this operator's metrics.
            ///
            /// Generated by `#[metrics_doc(...)]`. Used by the metrics
            /// documentation generator and by
            /// [`ExecutionPlan::metrics_documentation`].
            pub fn metrics_doc() -> &'static datafusion_doc::MetricsDocumentation {
                static DOC: std::sync::LazyLock<datafusion_doc::MetricsDocumentation> =
                    std::sync::LazyLock::new(|| {
                        datafusion_doc::MetricsDocumentation::builder(
                            #name_str,
                            #position_expr,
                        )
                        #description_expr
                        #(#metric_exprs)*
                        .build()
                    });
                &DOC
            }
        }
    }
    .into()
}
