# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# Tests for Docs that runs on PRs
name: Docs

concurrency:
  group: ${{ github.repository }}-${{ github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true

on:
  push:
    paths:
      - "docs/**"
    branches:
      - main
      - branch-*
  pull_request:
    paths:
      - "docs/**"
  # manual trigger
  # https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
  workflow_dispatch:

permissions:
  contents: read

jobs:
  # Test doc build
  linux-test-doc-build:
    name: Test doc build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          submodules: true
          fetch-depth: 1
      - name: Setup uv
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990  # v8.3.2
      - name: Install doc dependencies
        run: uv sync --package datafusion-docs
      - name: Install Graphviz
        run: |
          set -x
          sudo apt-get update
          sudo apt-get install -y graphviz
      - name: Install cargo-depgraph
        uses: taiki-e/install-action@a6b2e2dcd845ddd7f509ce4f3ed3d922b80cc5d9  # v2.84.0
        with:
          tool: cargo-depgraph@1.6
      - name: Build docs html and check for warnings
        run: |
          set -x
          cd docs
          uv run --package datafusion-docs ./build.sh # fails on errors
