# Downloads any `message` artifacts created by other jobs
# and posts them as comments to the PR
name: PR Comment

on:
  workflow_run:
    workflows: ["Benchmarks"]
    types:
      - completed

jobs:
  comment:
    name: PR Comment
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Download comment message
        uses: actions/download-artifact@v4
        with:
          name: message
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download pr number
        uses: actions/download-artifact@v4
        with:
          name: pr
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Print message and pr number
        run: |
          cat pr
          echo "PR_NUMBER=$(cat pr)" >> "$GITHUB_ENV"
          cat message.md

      - name: Post the comment
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const content = fs.readFileSync('message.md', 'utf8');
            github.rest.issues.createComment({
              issue_number: process.env.PR_NUMBER,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: content,
            })
